# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main

pool:
  name: SelfHostedPool  # Specify the name of your agent pool
  # vmImage: 'windows-latest' # azure hosted
jobs:
- job: Build
  steps:
  - script: echo "Building on a self-hosted agent!"